### ISSUE TITLE
July 13 Discussion: inital idea

### ISSUE THREAD

**Issue by v9n** [yeo/qCommander#1]
Mục đích:
- Control các slideshow trên các website hỗ trợ play slideshow như : slide.es, speakerdeck, slideshare.net. Ko phải dùng m$ office với remote riêng

Component:
- bookmarklet: chạy ở browser, mỗi khi người dùng vào website nào đó, họ bấm vào cái bookmark item, bookmarklet của mình sẽ chạy. Tiến  hành connect vào server, lấy về 1 unique token. Rồi trình diễn cho user(trên 1 overlay layer) dưới 2 dạng
  - 1 string
  - 1 qr code
- iOS app: từ main view, user có thể hoặc enter cái string trên thủ công, hoặc dùng camera để scan qr code. Mỗi khi scan xong thì tiến hành connect đến server, xác nhận pairingf với browser thành công, Lúc này, bookmarklet sẽ hide cái overlay  của nó trên browser đi, trả lại cái màn hình slideshow cho user. Còn iPhone thì chuyển sang màn hình tiếp theo với 5 nút: play/pause, next/previous, first, last và 1 số thông tin về slideshow.

**Comment by tinhspace** [comment]
Tao chưa nghĩ ra gì nhiều cả, chỉ cho mi biết là tao đã đọc và đang suy nghĩ về flow người dùng + tìm cách nào đó cho người ta giảm bớt số bước ở trên đi được không :D

**Comment by tinhspace** [comment]
Ý tưởng thêm để cân nhắc chọn lựa:
- Thanh trượt để có thể kéo tua nhanh thứ tự các Slide (nếu trường hợp muốn nhảy tới nhanh 1 slide nào đấy) - Lúc tua thì hiển thị ở màn hình iPhone cái số thứ tự của slide đó + nếu có thumbnail thì càng ngon lành
- Hoặc nhập vị trí slide vào để nhảy tới slide tương ứng
- Về button Next-Prev: Có thể thay thế bằng tính năng kéo qua trái/phải để next/prev slide (tương tự cách load ảnh mới trên Meme Storm bây giờ)
- Lúc chạy App lần đầu tiên, thì hiển thị thêm các tooltip ở các button tương ứng, cho người dùng biết chức năng chính của từng phần. Lần sau chạy App thì không hiển thị nữa

**Comment by v9n** [comment]
```
Tao chưa nghĩ ra gì nhiều cả, chỉ cho mi biết là tao đã đọc và đang suy nghĩ về flow người dùng + tìm cách nào đó cho người ta giảm bớt số bước ở trên đi được không :D
```

Giảm đc số thao tác thì tốt quá, hiện tại có 2 gd để app hoạt động:
1. pairing
2. control

Chuyện slide hay thumbnail...là những chức năng rất hat, và chắc chắn mình sẽ implement. N tao nghĩ khó có trong version đầu tiên được ;(. Tao nghĩ mình nên launch 1 sản phẩm với chức năng tối thiểu trước.

```
Lúc chạy App lần đầu tiên, thì hiển thị thêm các tooltip ở các button tương ứng, cho người dùng biết chức năng chính của từng phần. Lần sau chạy App thì không hiển thị nữa 
```

Những phần này thuộc về UI/UX mi cứ làm theo ý mi và tao sẽ implement trong iOS.

**Comment by tinhspace** [comment]
![ui](https://f.cloud.github.com/assets/236967/813818/7ab0ed1e-ef09-11e2-8c9b-939a1713821f.jpg)

Bản mockup đầu tiên nè, xem và góp ý cho tao nhé

**Comment by v9n** [comment]
amazing. Gonna love it. 

Feedback:
1. the button is so small: when speaking, the speaker is not gonna look at screen. So, has a big button, or an area for swiping will be easier. An area with a big image so users know they must swipe on it. We can put a toogle button  somewhere to switch between swiping and touching (checkout WD tv remote app)
2. My own opinion: 
   2.1 The scan and add pair string actually do the same purpose. So it can be  a little bit confusing now. Should we have sth like a connect button and user choose which ever method they like. but it adds more step for end-user. 

2.2 We should have at least 2 views. the first is connection view, that shows an insturction to let user know what they need to do. and connection button

But the design looks great overall.

**Comment by tinhspace** [comment]
Một số phần cần design thêm:
1. Lúc người dùng bật ứng dụng lên, thì lúc đó chưa có các thông tin về thứ tự Slide, Next, Back..., lúc đó mình sẽ hiển thị các hướng dẫn cho người dùng ( có thể swipe qua về để xem), bên dưới vẫn giữ vị trí button: Scan QR Code, Add Pair String --> Sau khi scan finish, pair với trình duyệt xong thì sẽ hiển thị đầy đủ các thông tin như Design bên trên

Cần suy nghĩ thêm về các nội dung hiển thị hướng dẫn ở đó là gì?
1. Có thêm button để chuyển đổi qua lại giữa 2 mode : Button và Touch 

Lúc hiển thị ở mode Touch, cần giải quyết vấn đề cho người mới sử dụng, đó là có các chỉ dẫn cơ bản nhất để sử dụng phần mềm

**Comment by v9n** [comment]
Tao nghi phần kết nối làm như cái App Remote của Apple á ;(. Rất hay và nhanh, mi coi thử đi.
