### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by tinhspace** [yeo/qCommander#39]
![qslider-icon-1](https://f.cloud.github.com/assets/236967/1955949/17f570d0-81f0-11e3-85cc-13612560f274.png)
![qslider-icon-2](https://f.cloud.github.com/assets/236967/1955950/1802433c-81f0-11e3-8692-d569868b7c6f.png)
![qslider-icon-3](https://f.cloud.github.com/assets/236967/1955951/180f37e0-81f0-11e3-92af-5e1feadb800f.png)
![qslider-icon-4](https://f.cloud.github.com/assets/236967/1955952/181b0624-81f0-11e3-99e8-f269d6612d30.png)
![qslider-icon-5](https://f.cloud.github.com/assets/236967/1955953/18288a88-81f0-11e3-8cef-79dbe6734f66.png)

**Comment by tinhspace** [comment]
@kureikain Coi thích cái nào thì dùng nhé :+1:

**Comment by v9n** [comment]
+1

https://f.cloud.github.com/assets/236967/1955953/18288a88-81f0-11e3-8cef-79dbe6734f66.png

**Comment by v9n** [comment]
2 cái icon cuối tao thấy đẹp mà unique nữa. Mấy cái icon ở trên khó làm branding đc quá. 
T cũng khoái kiểu text logo (như Quora, Instapaper,..) nên sẽ chọn cái cuối cùng (y)
