### ISSUE TITLE
App Images for Intro

### ISSUE THREAD

**Issue by tinhspace** [yeo/qCommander#40]
![intro-1](https://f.cloud.github.com/assets/236967/1956688/cb49c2c0-81fb-11e3-84db-1a43bfdd9a15.png)

![intro](https://f.cloud.github.com/assets/236967/1956439/01548250-81f8-11e3-847c-a711c1a95f19.png)

![step-1](https://f.cloud.github.com/assets/236967/1956522/675d0f1c-81f9-11e3-8641-7afe24cb1d6c.png)

![step-2](https://f.cloud.github.com/assets/236967/1956523/67820402-81f9-11e3-805c-feb7d871825b.png)

![step-3](https://f.cloud.github.com/assets/236967/1956524/6793926c-81f9-11e3-819b-e65c87ea3a33.png)

![lockscreen-phone-white](https://f.cloud.github.com/assets/236967/1956168/ff86b7f8-81f3-11e3-9c87-4a7cd09cc388.png)

![pair-phone-white](https://f.cloud.github.com/assets/236967/1956170/ffbe2954-81f3-11e3-8083-ed202b08e9c6.png)

![phone_small](https://f.cloud.github.com/assets/236967/1956171/fff5ec72-81f3-11e3-824b-16975c2092dc.png)

![slider-phone-white](https://f.cloud.github.com/assets/236967/1956172/000336fc-81f4-11e3-8d36-dd0d657682eb.png)

![qrcode-phone-white](https://f.cloud.github.com/assets/236967/1956241/a8815f66-81f4-11e3-8e7b-a88e5b5bad68.png)

![thanks-phone-white](https://f.cloud.github.com/assets/236967/1956173/0013ebd2-81f4-11e3-9628-2160397a921e.png)

**Comment by tinhspace** [comment]
## Các hình ảnh dùng để sử dụng cho Website và Clip Giới Thiệu

**Comment by v9n** [comment]
@tinh Mi change chữ qSlider thành QSlider nha? Đổi tên rồi mi :D

**Comment by v9n** [comment]
These images used for video. Checkout https://axcoto.com/qslider/
